name: Create and publish tic-tac-toe-backend Docker image

on: [push]


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ci-cd-dhbw-hdh-pschoeppner/reporeporepo-backend
  CONTAINER_NAME: ${{ github.event.repository.name }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

     # - name: Build gradle
      #  run: gradle build -Dquarkus.package.type=native

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

     # - name: Build and push Docker image
      #  uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      #  with:
     #     context: .
      #    file: src/main/docker/Dockerfile.native
      #    push: true
      #    tags: ${{ steps.meta.outputs.tags }}
      #    labels: ${{ steps.meta.outputs.labels }}
      
      
  deploy-to-digital-ocean:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Display settings
        run: |
          echo $(echo REGISTRY=$REGISTRY)
          echo $(echo CONTAINER_NAME=$CONTAINER_NAME)
          echo $(echo IMAGE_NAME=$IMAGE_NAME)  
      - name: DigitalOcean App Platform deployment
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          
          script: |
            docker stop $(echo $CONTAINER_NAME)
            docker rm $(echo $CONTAINER_NAME)
            docker pull ghcr.io/ci-cd-dhbw-hdh-pschoeppner/reporeporepo-backend:master
            docker run -d --restart always --name $CONTAINER_NAME ghcr.io/ci-cd-dhbw-hdh-pschoeppner/reporeporepo-backend:master
